# Generated by Django 5.2.15 on 2026-07-10 21:55

from django.db import migrations, models


def backfill_username(apps, schema_editor):
    """Isi snapshot username baris lama dari FK yang masih hidup."""
    AuditLog = apps.get_model('core', 'AuditLog')
    for log in AuditLog.objects.exclude(user=None).select_related('user'):
        log.username = log.user.username
        log.save(update_fields=['username'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='username',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.RunPython(backfill_username, migrations.RunPython.noop),
    ]
