# Generated by Django 5.2.15 on 2026-07-18 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0009_upload_duplicate_transactions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FRKoreksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tanggal', models.DateField()),
                ('account', models.CharField(max_length=255)),
                ('kolom', models.CharField(max_length=64)),
                ('nilai', models.DecimalField(decimal_places=2, max_digits=18)),
                ('alasan', models.CharField(blank=True, choices=[('cutoff_mutation', 'Cutoff Mutation'), ('mistake_cs', 'Mistake CS'), ('biaya_admin_bank', 'Biaya Admin Bank'), ('biaya_admin_qris', 'Biaya Admin QRIS'), ('dana_pending', 'Dana Pending'), ('cm_pindah_dana', 'Sesama CM (Pindah Dana)'), ('cm_naik_tampung', 'Sesama CM (Naik Tampung)'), ('cm_turun_tampung', 'Sesama CM (Turun Tampung)'), ('bank_title_beda', 'Bank Title Tidak Sesuai'), ('lainnya', 'Lainnya')], max_length=32)),
                ('catatan', models.TextField(blank=True)),
                ('dibuat_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fr_koreksi', to=settings.AUTH_USER_MODEL)),
                ('toko', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fr_koreksi', to='sources.toko')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('toko', 'tanggal', 'account', 'kolom'), name='uniq_fr_koreksi_sel')],
            },
        ),
    ]
