# Generated by Django 5.2.15 on 2026-07-26 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0012_seed_toko_panel'),
        ('web', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RekapPenyebab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('periode', models.DateField(help_text='tanggal 1 bulan bersangkutan')),
                ('label', models.CharField(max_length=100)),
                ('nilai', models.DecimalField(decimal_places=2, max_digits=18)),
                ('urutan', models.PositiveSmallIntegerField(default=0)),
                ('toko', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rekap_penyebab', to='sources.toko')),
            ],
            options={
                'ordering': ['urutan', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RekapManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('periode', models.DateField(help_text='tanggal 1 bulan bersangkutan')),
                ('field', models.CharField(help_text='slug baris web.rekap.FIELDS', max_length=64)),
                ('nilai', models.DecimalField(decimal_places=2, max_digits=18)),
                ('catatan', models.TextField(blank=True)),
                ('dibuat_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rekap_manual', to=settings.AUTH_USER_MODEL)),
                ('toko', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rekap_manual', to='sources.toko')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('toko', 'periode', 'field'), name='uniq_rekap_manual')],
            },
        ),
    ]
