# Generated by Django 5.2.15 on 2026-07-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('sources', '0006_backfill_toko'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allowed_tokos',
            field=models.ManyToManyField(blank=True, help_text='Toko yang boleh diakses (hanya relevan untuk auditor)', related_name='assigned_users', to='sources.toko'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('supervisor', 'Supervisor'), ('auditor', 'Auditor')], default='auditor', max_length=20),
        ),
    ]
