# Generated by Django 5.2.15 on 2026-07-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_supervisor_allowed_tokos'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Wajib ganti password saat login berikutnya (password sementara dari admin).'),
        ),
    ]
