# Generated by Django 5.2.15 on 2026-06-30 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToleranceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('date_window_days', models.IntegerField(default=1)),
                ('date_direction', models.CharField(default='target_after_base', help_text='target_after_base = sisi uang (Bank) >= sisi kredit (Panel)', max_length=30)),
                ('amount_abs_tol', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('amount_pct_tol', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('fuzzy_threshold', models.IntegerField(default=85)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MatchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relation', models.CharField(choices=[('panel_bracket', 'Panel <-> Bracket'), ('panel_bank', 'Panel <-> Bank/Gateway'), ('bracket_bank', 'Bracket <-> Bank/Gateway'), ('saldo', 'Rekonsiliasi Saldo')], max_length=20)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('params', models.JSONField(default=dict)),
                ('summary', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tolerance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reconciliation.toleranceprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bucket', models.CharField(choices=[('cocok', 'Cocok'), ('tidak_cocok', 'Tidak Cocok'), ('perlu_tinjau', 'Perlu Ditinjau')], max_length=15)),
                ('score', models.FloatField(default=0)),
                ('reason_code', models.CharField(blank=True, max_length=50)),
                ('reason_detail', models.TextField(blank=True)),
                ('left', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='transactions.transaction')),
                ('right', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='transactions.transaction')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='reconciliation.matchrun')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=30)),
                ('reason', models.TextField(blank=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reconciliation.matchresult')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
