# Generated by Django 5.2.15 on 2026-07-02 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0002_seed_tolerance'),
        ('sources', '0006_backfill_toko'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchrun',
            name='relation',
            field=models.CharField(choices=[('panel_bracket', 'Panel ↔ Bracket'), ('panel_bank', 'Panel ↔ Bank/Gateway'), ('bracket_bank', 'Bracket ↔ Bank/Gateway'), ('saldo', 'Rekonsiliasi Saldo')], max_length=20),
        ),
        migrations.CreateModel(
            name='ReconBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('summary', models.JSONField(default=dict)),
                ('completeness', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('toko', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sources.toko')),
                ('tolerance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reconciliation.toleranceprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='matchrun',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='reconciliation.reconbatch'),
        ),
    ]
