# Generated by Django 5.2.15 on 2026-07-04 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0003_alter_matchrun_relation_reconbatch_matchrun_batch'),
        ('sources', '0007_seed_16_toko'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresult',
            name='resolved_by_batch',
            field=models.ForeignKey(blank=True, help_text='Batch yang men-settle hasil tidak_cocok/no_money ini terlambat', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_results', to='reconciliation.reconbatch'),
        ),
        migrations.AddField(
            model_name='reconbatch',
            name='recon_date',
            field=models.DateField(blank=True, db_index=True, help_text='Tanggal rekonsiliasi harian — satu batch per (toko, tanggal)', null=True),
        ),
        migrations.AddConstraint(
            model_name='reconbatch',
            constraint=models.UniqueConstraint(condition=models.Q(('recon_date__isnull', False)), fields=('toko', 'recon_date'), name='uniq_reconbatch_toko_recon_date'),
        ),
    ]
