# Generated by Django 5.2.15 on 2026-07-05 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0003_alter_matchrun_relation_reconbatch_matchrun_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconbatch',
            name='include',
            field=models.JSONField(blank=True, help_text='sumber yang diikutkan saat run (None = semua, legacy)', null=True),
        ),
    ]
