# Generated by Django 5.2.15 on 2026-07-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0004_matchresult_resolved_by_batch_reconbatch_recon_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchrun',
            name='relation',
            field=models.CharField(choices=[('panel_bracket', 'Panel ↔ Bracket'), ('panel_bank', 'Panel ↔ Mutasi Bank'), ('bracket_bank', 'Bracket ↔ Mutasi Bank'), ('saldo', 'Rekonsiliasi Saldo')], max_length=20),
        ),
    ]
