# Generated by Django 5.2.15 on 2026-07-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0004_reconbatch_include'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconbatch',
            name='error_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reconbatch',
            name='status',
            field=models.CharField(choices=[('berjalan', 'Berjalan'), ('selesai', 'Selesai'), ('gagal', 'Gagal')], default='selesai', max_length=10),
        ),
    ]
