# Generated by Django 5.2.15 on 2026-07-21 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0005_alter_matchrun_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewaction',
            name='alasan',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
