# Generated by Django 5.2.15 on 2026-08-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0006_reviewaction_alasan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchrun',
            name='relation',
            field=models.CharField(choices=[('panel_bracket', 'Panel ↔ Bracket'), ('panel_bank', 'Panel ↔ Mutasi Bank'), ('fr_bank', 'Bracket ↔ Mutasi Bank'), ('bracket_bank', 'Sesama CM ↔ Mutasi Bank'), ('saldo', 'Rekonsiliasi Saldo')], max_length=20),
        ),
    ]
