# Generated by Django 5.2.15 on 2026-06-30 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('occurred_at', models.DateTimeField(blank=True, help_text='Waktu transaksi asli', null=True)),
                ('posted_date', models.DateField(blank=True, help_text="Tanggal 'masuk' (statement/entry)", null=True)),
                ('jenis', models.CharField(choices=[('depo', 'Deposit'), ('wd', 'Withdraw'), ('bonus', 'Bonus'), ('admin', 'Biaya Admin'), ('mistake', 'Mistake'), ('lainnya', 'Lainnya')], default='lainnya', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('credit_delta', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('money_delta', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('ticket_no', models.CharField(blank=True, db_index=True, max_length=64)),
                ('username', models.CharField(blank=True, db_index=True, max_length=100)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=128)),
                ('counterparty', models.CharField(blank=True, help_text='nama pengirim/penerima di bank', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('raw', models.JSONField(default=dict, help_text='baris asli (telusur balik)')),
                ('row_hash', models.CharField(db_index=True, help_text='guard idempotensi re-import', max_length=64)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sources.account')),
                ('source_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sources.sourcetype')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='sources.upload')),
            ],
            options={
                'indexes': [models.Index(fields=['source_type', 'occurred_at'], name='transaction_source__e1eee4_idx'), models.Index(fields=['jenis', 'amount'], name='transaction_jenis_a0e0c1_idx')],
            },
        ),
    ]
