# Generated by Django 5.2.15 on 2026-07-04 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0003_alter_matchrun_relation_reconbatch_matchrun_batch'),
        ('transactions', '0002_transaction_toko'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='consumed_by_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumed_transactions', to='reconciliation.reconbatch'),
        ),
    ]
