# Generated by Django 5.2.15 on 2026-07-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_consumed_by_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='bank_title',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='transaction',
            name='player_bank',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
