# Generated by Django 5.2.15 on 2026-07-04 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_consumed_by_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='dest_account',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
    ]
