# Generated by Django 5.2.15 on 2026-07-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0005_alter_matchrun_relation'),
        ('sources', '0007_seed_16_toko'),
        ('transactions', '0005_backfill_bank_fields'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('source_type', 'toko', 'row_hash'), name='uniq_tx_source_toko_rowhash'),
        ),
    ]
