"""
Django settings for truth_auditor project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-wb5cb68!r##d-ht+w%ahp=(1ot)$o$p-rz&h6uj3stjc@+)ql5',
)

# SECURITY WARNING: don't run with debug turned on in production!
# Di Railway (RAILWAY_ENVIRONMENT selalu di-inject) default-nya PRODUKSI:
# service tanpa env DEBUG tak boleh diam-diam boot dengan DEBUG=True.
_default_debug = 'False' if os.environ.get('RAILWAY_ENVIRONMENT') else 'True'
DEBUG = os.environ.get('DEBUG', _default_debug).lower() == 'true'

# Produksi wajib SECRET_KEY dari env — kunci default di atas ter-commit di repo
# (publik). Gagal cepat saat boot jauh lebih aman daripada diam-diam insecure.
if not DEBUG and 'SECRET_KEY' not in os.environ:
    from django.core.exceptions import ImproperlyConfigured

    raise ImproperlyConfigured(
        'DEBUG=False tanpa env SECRET_KEY — set SECRET_KEY di environment produksi '
        '(jangan memakai kunci default repo).'
    )

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0', 'testserver']
_railway_host = os.environ.get('RAILWAY_PUBLIC_DOMAIN')
if _railway_host:
    ALLOWED_HOSTS.append(_railway_host)
ALLOWED_HOSTS += [h.strip() for h in os.environ.get('ALLOWED_HOSTS', '').split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    # local apps
    'core',
    'accounts',
    'sources',
    'transactions',
    'reconciliation',
    'reports',
    'web',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'web.middleware.GeoBlockMiddleware',
    'web.middleware.ForcePasswordChangeMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'truth_auditor.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'web.context_processors.toko',
                'web.context_processors.motivation',
            ],
        },
    },
]

WSGI_APPLICATION = 'truth_auditor.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Railway/produksi: pakai DATABASE_URL (Postgres) bila tersedia.
_db_url = os.environ.get('DATABASE_URL')
if _db_url:
    import dj_database_url

    DATABASES['default'] = dj_database_url.parse(_db_url, conn_max_age=600)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# Bahasa Indonesia: intcomma/floatformat memakai pemisah ribuan titik (Rp 1.234.567)
LANGUAGE_CODE = 'id'

# Nix/Nixpacks glibc (prod Railway) tidak mencari tzdata di /usr/share/zoneinfo
# secara default → TZ=Asia/Jakarta gagal di-resolve, fallback ke UTC, sehingga
# datetime.now() (USE_TZ=False) mundur 7 jam. Arahkan TZDIR ke tzdata yang ada
# SEBELUM Django memanggil time.tzset(), supaya waktu server benar-benar WIB (UTC+7).
if os.path.isdir('/usr/share/zoneinfo'):
    os.environ.setdefault('TZDIR', '/usr/share/zoneinfo')

TIME_ZONE = 'Asia/Jakarta'

USE_I18N = True

USE_TZ = False  # data bank/panel = waktu lokal (WIB) naif; single-region


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage'},
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- Truth of Auditor ---
AUTH_USER_MODEL = 'accounts.User'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = 'login'

# Token CSRF basi (tab lama/redeploy): logout diselesaikan, lainnya halaman ramah.
CSRF_FAILURE_VIEW = 'web.views.csrf_failure'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# --- Produksi / Railway ---
CSRF_TRUSTED_ORIGINS = []
if _railway_host:
    CSRF_TRUSTED_ORIGINS.append(f'https://{_railway_host}')
CSRF_TRUSTED_ORIGINS += [o.strip() for o in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()]

# --- Geo-block (kunci wilayah, fitur K4) ---
# DEFAULT MATI: middleware pass-through total — deploy tidak mengubah akses apa
# pun sampai env dinyalakan. GEO_BLOCK_COUNTRIES = daftar negara yang DIIZINKAN
# (allowlist, kode ISO 2-huruf); IP dari negara di luar daftar dapat 403 saat
# fitur menyala. DEFAULT 'ID' (Indonesia = basis pengguna nyata): menyalakan
# GEO_BLOCK_ENABLED saja tetap MENGIZINKAN pengguna Indonesia dan memblok
# sisanya (termasuk KH) — jangan set 'KH' di sini, itu akan memblok semua
# auditor Indonesia dan hanya mengizinkan Kamboja.
GEO_BLOCK_ENABLED = os.environ.get('GEO_BLOCK_ENABLED', 'False').lower() == 'true'
GEO_BLOCK_COUNTRIES = {
    c.strip().upper() for c in os.environ.get('GEO_BLOCK_COUNTRIES', 'ID').split(',') if c.strip()
}
GEO_BLOCK_ALLOWLIST = [x.strip() for x in os.environ.get('GEO_BLOCK_ALLOWLIST', '').split(',') if x.strip()]
GEO_BLOCK_BYPASS_STAFF = os.environ.get('GEO_BLOCK_BYPASS_STAFF', 'True').lower() == 'true'

# Traceback error 500 harus muncul di log Railway (default Django dengan
# DEBUG=False hanya mengirim ke email ADMINS — tidak pernah terlihat di log).
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {'class': 'logging.StreamHandler'},
    },
    'root': {'handlers': ['console'], 'level': 'WARNING'},
    'loggers': {
        'django.request': {'handlers': ['console'], 'level': 'ERROR', 'propagate': False},
    },
}

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'True').lower() == 'true'
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '0'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = SECURE_HSTS_SECONDS > 0
    SECURE_HSTS_PRELOAD = SECURE_HSTS_SECONDS > 0
