"""
Django settings for truth_auditor project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# DEBUG fail-safe: di Railway (env RAILWAY_* ada) default False — env DEBUG
# hilang tidak boleh membocorkan stack trace + settings ke publik. Lokal tetap
# default True supaya `runserver` zero-config.
_on_railway = bool(
    os.environ.get('RAILWAY_PUBLIC_DOMAIN') or os.environ.get('RAILWAY_ENVIRONMENT')
)
DEBUG = os.environ.get('DEBUG', 'False' if _on_railway else 'True').lower() == 'true'

# SECURITY WARNING: keep the secret key used in production secret!
# Produksi (DEBUG=False) tanpa env SECRET_KEY = ImproperlyConfigured saat boot.
from truth_auditor.security import resolve_secret_key  # noqa: E402

SECRET_KEY = resolve_secret_key(os.environ, DEBUG)

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0', 'testserver']
_railway_host = os.environ.get('RAILWAY_PUBLIC_DOMAIN')
if _railway_host:
    ALLOWED_HOSTS.append(_railway_host)
    # Healthcheck Railway memakai Host ini — tanpa entri ini deploy selalu
    # dianggap gagal (400 DisallowedHost) dan tidak pernah menerima traffic.
    ALLOWED_HOSTS.append('healthcheck.railway.app')
ALLOWED_HOSTS += [h.strip() for h in os.environ.get('ALLOWED_HOSTS', '').split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'axes',
    # local apps
    'core',
    'accounts',
    'sources',
    'transactions',
    'reconciliation',
    'reports',
    'web',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'core.middleware.ContentSecurityPolicyMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',
]

ROOT_URLCONF = 'truth_auditor.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'web.context_processors.toko',
            ],
        },
    },
]

WSGI_APPLICATION = 'truth_auditor.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Railway/produksi: pakai DATABASE_URL (Postgres) bila tersedia.
_db_url = os.environ.get('DATABASE_URL')
if _db_url:
    import dj_database_url

    DATABASES['default'] = dj_database_url.parse(_db_url, conn_max_age=600)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Jakarta'

USE_I18N = True

USE_TZ = False  # data bank/panel = waktu lokal (WIB) naif; single-region


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage'},
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- Truth of Auditor ---
AUTH_USER_MODEL = 'accounts.User'

# --- Brute-force login (django-axes) ---
# Off saat suite tes (client.login() tanpa request tidak kompatibel dgn backend
# axes); tes lockout sendiri menyalakannya via override_settings.
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]
AXES_ENABLED = 'test' not in sys.argv
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 1  # jam; lockout lepas sendiri
AXES_RESET_ON_SUCCESS = True
AXES_LOCKOUT_PARAMETERS = [['username', 'ip_address']]  # kunci kombo user+IP

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = 'login'

# Token CSRF basi (tab lama/redeploy): logout diselesaikan, lainnya halaman ramah.
CSRF_FAILURE_VIEW = 'web.views.csrf_failure'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# --- Sesi: data finansial, jangan hidup 2 minggu (default Django) ---
SESSION_COOKIE_AGE = 8 * 3600          # idle timeout 8 jam...
SESSION_SAVE_EVERY_REQUEST = True      # ...digeser tiap request (rolling)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Picker folder (webkitdirectory) bisa kirim ratusan file; default Django 100.
DATA_UPLOAD_MAX_NUMBER_FILES = 500

# --- Logging: stdout terstruktur (Railway menangkap console) ---
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {'class': 'logging.StreamHandler', 'formatter': 'verbose'},
    },
    'root': {'handlers': ['console'], 'level': 'INFO'},
    'loggers': {
        # 4xx/5xx + unhandled exception tampil di log deploy, bukan menguap.
        'django.request': {'handlers': ['console'], 'level': 'WARNING', 'propagate': False},
    },
}

# --- Produksi / Railway ---
CSRF_TRUSTED_ORIGINS = []
if _railway_host:
    CSRF_TRUSTED_ORIGINS.append(f'https://{_railway_host}')
CSRF_TRUSTED_ORIGINS += [o.strip() for o in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()]

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'True').lower() == 'true'
    # Healthcheck internal Railway datang tanpa X-Forwarded-Proto — jangan
    # di-redirect ke https (301 = healthcheck gagal).
    SECURE_REDIRECT_EXEMPT = [r'^healthz$']
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = SECURE_HSTS_SECONDS > 0
    SECURE_HSTS_PRELOAD = SECURE_HSTS_SECONDS > 0
