# Generated by Django 5.2.15 on 2026-06-30 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('bank', 'Bank'), ('gateway', 'Gateway')], max_length=10)),
                ('provider', models.CharField(help_text='BRI / BCA / MANDIRI / NXPAY / QRFLYER', max_length=50)),
                ('name', models.CharField(help_text="Label/pemilik, mis. 'BCA HENDI'", max_length=100)),
                ('account_no', models.CharField(blank=True, max_length=64)),
                ('flow', models.CharField(choices=[('dp', 'Deposit'), ('wd', 'Withdraw'), ('both', 'Both')], default='both', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('panel', 'Panel'), ('bracket', 'Bracket'), ('bank', 'Bank'), ('gateway', 'Gateway')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_money_source', models.BooleanField(default=False, help_text='Bank & gateway = sumber kebenaran uang')),
            ],
        ),
        migrations.CreateModel(
            name='ColumnTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('header_row', models.IntegerField(default=1, help_text='Baris (1-based) tempat header')),
                ('mapping', models.JSONField(default=dict, help_text='canonical_field -> nama kolom sumber')),
                ('jenis_resolver', models.JSONField(default=dict, help_text="cara tentukan 'jenis'")),
                ('number_format', models.CharField(choices=[('intl', '1,000.00 (intl)'), ('id', '1.000,00 (ID)')], default='intl', max_length=5)),
                ('date_formats', models.JSONField(default=list, help_text='kandidat format tanggal')),
                ('amount_scale', models.IntegerField(default=1, help_text='kalikan amount agar jadi rupiah (Panel=1000)')),
                ('is_default', models.BooleanField(default=False)),
                ('source_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='sources.sourcetype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flow', models.CharField(blank=True, max_length=5)),
                ('recon_date', models.DateField(blank=True, help_text='tanggal rekonsiliasi', null=True)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('parsed', 'Parsed'), ('error', 'Error')], default='uploaded', max_length=10)),
                ('rows_parsed', models.IntegerField(default=0)),
                ('rows_duplicate', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sources.account')),
                ('source_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sources.sourcetype')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sources.columntemplate')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
