# Generated by Django 5.2.15 on 2026-07-02 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0004_seed_toko'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='toko',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sources.toko'),
        ),
        migrations.AddField(
            model_name='upload',
            name='provider',
            field=models.CharField(blank=True, help_text='Panel provider, mis. Nexus', max_length=50),
        ),
        migrations.AddField(
            model_name='upload',
            name='toko',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sources.toko'),
        ),
    ]
