# Generated by Django 5.2.15 on 2026-07-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0007_seed_16_toko'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='owner_name',
            field=models.CharField(blank=True, help_text='Nama pemilik rekening dari header file (mis. HENDI) atau nama file', max_length=100),
        ),
    ]
