# Generated by Django 5.2.15 on 2026-07-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0008_upload_owner_name'),
        ('transactions', '0007_transaction_uniq_tx_source_rowhash_toko_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='duplicate_transactions',
            field=models.ManyToManyField(blank=True, related_name='duplicated_in_uploads', to='transactions.transaction'),
        ),
    ]
