# Generated by Django 5.2.15 on 2026-08-01 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0012_seed_toko_panel'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='superseded_by',
            field=models.ForeignKey(blank=True, help_text="Terisi bila file ini 'ketiban' upload ulang sama-nama yang lebih lengkap", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='sources.upload'),
        ),
    ]
