"""Kumpulan kalimat motivasi untuk toast — nuansa audit (mayoritas) + kerja umum.

Ditata sebagai dua daftar agar mudah ditambah menuju 1000+ tanpa mengubah kode lain.
Satu kalimat dipilih acak per pemuatan halaman (lihat context_processors.motivation).
Semua kalimat Bahasa Indonesia, tanpa duplikat (dijaga oleh web/tests_motivation.py).
"""
import random

# Nuansa audit: ketelitian, integritas, rekonsiliasi, akurasi, kesabaran, tanggung jawab.
AUDIT = [
    "Setiap angka menyimpan cerita; tugas kita memastikan ceritanya benar.",
    "Ketelitian hari ini adalah ketenangan esok hari.",
    "Selisih sekecil apa pun layak ditanya, bukan diabaikan.",
    "Rekonsiliasi bukan mencari yang salah, melainkan memastikan semuanya benar.",
    "Data yang rapi lahir dari auditor yang sabar.",
    "Percaya boleh, memverifikasi wajib.",
    "Satu baris yang cocok hari ini adalah satu masalah yang tak meledak nanti.",
    "Integritas adalah laporan yang tetap sama meski tak ada yang mengawasi.",
    "Angka tidak pernah berbohong; yang berbohong adalah yang enggan mencocokkannya.",
    "Teliti di awal jauh lebih murah daripada memperbaiki di akhir.",
    "Kejujuran sebuah catatan diuji saat ia berani dicocokkan.",
    "Auditor hebat bukan yang tercepat, tetapi yang tak melewatkan.",
    "Setiap transaksi yang kau tinjau menjaga kepercayaan seseorang.",
    "Ragu sedikit lalu memeriksa lagi adalah tanda profesional, bukan tanda lemah.",
    "Konsistensi kecil setiap hari mengalahkan usaha besar sesekali.",
    "Yang tidak cocok bukanlah musuh, melainkan petunjuk.",
    "Bereskan selisih hari ini agar besok bekerja dengan tenang.",
    "Ketelitian adalah bentuk hormat pada uang orang lain.",
    "Banyak rekening, satu standar ketelitian.",
    "Sabar menelusuri, lega menemukan.",
    "Tutup buku dengan hati tenang: semuanya sudah dicocokkan.",
    "Kualitas audit terlihat justru saat tak ada yang memeriksa ulang.",
    "Selisih yang dibiarkan akan tumbuh; selisih yang dikejar akan hilang.",
    "Fokus pada yang janggal, tenang pada yang wajar.",
    "Setiap centang adalah janji bahwa angka ini benar.",
    "Mencocokkan satu per satu memang lambat, tetapi tak pernah keliru arah.",
    "Bukti mengalahkan asumsi, selalu.",
    "Kalau ragu, telusuri sampai ujung.",
    "Angka yang benar tidak takut diperiksa dua kali.",
    "Rapikan datamu, maka pikiranmu ikut jernih.",
    "Ketekunan adalah bakat yang paling bisa diandalkan seorang auditor.",
    "Hari yang baik bagi auditor adalah saat semua kolom bertemu pasangannya.",
    "Jangan percaya pada ingatan; percaya pada catatan yang tercocokkan.",
    "Selisih nol bukan keberuntungan, melainkan hasil ketelitian.",
    "Satu kesalahan yang ditemukan lebih berharga daripada seratus tebakan.",
    "Pekerjaan yang teliti jarang bersuara, tetapi selalu terasa.",
    "Menunda memeriksa hanya menumpuk pekerjaan untuk diri sendiri.",
    "Kepercayaan dibangun dari ribuan pencocokan yang tak terlihat.",
    "Yang penting bukan seberapa cepat selesai, tetapi seberapa bisa dipertanggungjawabkan.",
    "Auditor yang baik tidur nyenyak karena angkanya sudah bertemu.",
    "Di balik setiap laporan bersih ada auditor yang menolak menyerah pada selisih.",
    "Curiga yang sehat adalah alat kerja, bukan sifat buruk.",
    "Kecil bagi orang lain, besar bagi auditor: satu rupiah yang tak cocok.",
    "Ketelitian bukan kelambatan; ia adalah kecepatan yang tidak perlu diulang.",
    "Cocokkan sekarang selagi jejaknya masih hangat.",
    "Setiap kolom punya alasan; jangan lewati tanpa mengerti.",
    "Yang tak terjelaskan hari ini adalah pekerjaan rumah untuk besok.",
    "Disiplin mencatat mengalahkan kecerdikan mengingat.",
    "Angka yang jujur tidak butuh dibela, cukup dicocokkan.",
    "Pelan boleh, asalkan tak ada yang terlewat.",
    "Ketelitian adalah janji diam-diam kepada orang yang memercayaimu.",
    "Bukan berapa banyak yang kau periksa, tetapi berapa yang kau pastikan.",
    "Selisih adalah pertanyaan; tugas kita menemukan jawabannya.",
    "Rekonsiliasi yang tuntas hari ini menghemat penjelasan panjang esok hari.",
    "Angka yang rapi adalah wajah dari kerja yang jujur.",
    "Jangan tanda tangani yang belum kau mengerti.",
    "Kesabaran seorang auditor diukur dari baris terakhir, bukan yang pertama.",
    "Yang benar akan cocok; yang cocok belum tentu benar, maka periksalah.",
    "Setiap berkas yang kau rapikan meringankan orang setelahmu.",
    "Ketelitian tidak menuntut kecerdasan luar biasa, hanya keteguhan biasa yang diulang.",
    "Menemukan satu selisih terasa melelahkan, tetapi menyembunyikannya jauh lebih berat.",
    "Bekerja bersih hari ini adalah hadiah untuk dirimu di akhir bulan.",
    "Kepercayaan itu mahal; ketelitian adalah cara kita membayarnya.",
    "Jangan biarkan angka yang aneh berlalu hanya karena lelah.",
    "Auditor menutup celah sebelum celah itu menutup peluang.",
    "Yang rapi di layar berawal dari yang teliti di kepala.",
    "Setiap rekonsiliasi adalah percakapan jujur antara dua catatan.",
    "Ketelitian adalah keberanian memeriksa ulang saat semua orang sudah puas.",
    "Selesaikan yang menggantung; catatan yang bersih tidur lebih nyenyak.",
    "Tak ada angka yang terlalu kecil untuk diperhatikan seorang auditor.",
    "Kerja teliti tidak selalu dipuji, tetapi selalu menyelamatkan.",
    "Kebenaran satu transaksi lebih berharga daripada seribu perkiraan.",
    "Auditor tidak menebak; auditor menelusuri.",
    "Sedikit sabar di depan layar, banyak tenang di akhir hari.",
    "Yang tidak dicatat mudah dilupakan; yang dilupakan sulit dipertanggungjawabkan.",
    "Ketelitian adalah disiplin yang memilih benar di atas cepat.",
    "Cocok itu memuaskan; mengerti mengapa cocok itu mendewasakan.",
    "Jangan lawan selisih dengan asumsi; lawan dengan bukti.",
    "Setiap baris yang beres adalah satu batu di fondasi kepercayaan.",
    "Auditor yang teliti membuat angka berbicara jujur.",
    "Kerja hari ini bukan sekadar mencocokkan, tetapi menjaga nama baik.",
    "Yang penting terselesaikan dengan benar, bukan sekadar terselesaikan.",
    "Ragu adalah undangan untuk memeriksa, bukan alasan untuk berhenti.",
    "Ketelitian menua dengan baik; kesembronoan menua jadi masalah.",
    "Setiap selisih yang kau tutup adalah pintu yang kau kunci dari kekeliruan.",
    "Bekerja dengan bukti membuat tidur lebih tenang daripada bekerja dengan harapan.",
    "Angka yang benar tidak minta dipercaya; ia minta diperiksa.",
    "Auditor menjaga yang kecil agar yang besar tetap benar.",
    "Ketelitian adalah cara paling sunyi untuk menjaga kejujuran.",
    "Yang kau cocokkan hari ini adalah yang tak perlu kau jelaskan besok.",
    "Selisih tak pernah hilang karena diabaikan; ia hanya menunggu.",
    "Kesungguhan seorang auditor tampak pada baris yang paling membosankan.",
    "Data bersih adalah hasil dari seribu keputusan kecil untuk tidak menyerah.",
    "Periksa seolah orang lain akan memeriksa pekerjaanmu, karena bisa jadi begitu.",
    "Setiap koin punya jejak; ikuti sampai bertemu pasangannya.",
    "Menyerah pada selisih hari ini berarti mewariskannya pada dirimu sendiri.",
    "Ketelitian bukan tujuan sekali jadi, melainkan kebiasaan setiap hari.",
    "Angka yang dijaga dengan jujur menjaga orang yang menjaganya.",
    "Auditor sejati membaca yang tersirat di antara dua saldo.",
    "Yang benar cukup dicocokkan; yang keliru cukup ditemukan.",
    "Kesabaran menelusuri hari ini menumbuhkan ketenangan sepanjang pekan.",
    "Setiap laporan adalah tanda tangan diam atas ketelitianmu.",
    "Jangan biarkan lelah memutuskan mana angka yang layak diperiksa.",
    "Ketelitian adalah bentuk kasih sayang pada pekerjaan yang serius.",
    "Menutup buku tanpa selisih adalah kemewahan yang lahir dari ketekunan.",
    "Bukti hari ini menghapus keraguan besok.",
    "Auditor tak mengejar sempurna; ia mengejar yang benar-benar cocok.",
    "Kejujuran angka dimulai dari keberanian mencocokkannya apa adanya.",
    "Setiap detail yang kau hormati membalasmu dengan ketenangan.",
    "Yang tekun mencocokkan jarang terkejut di akhir bulan.",
    "Ketelitian adalah investasi yang bunganya berupa tidur nyenyak.",
    "Angka yang rapi tak pernah kebetulan; ia selalu diperjuangkan.",
    "Setiap selisih yang terjawab menambah satu alasan untuk dipercaya.",
    "Auditor menutup hari dengan pertanyaan yang sudah dijawab, bukan yang ditunda.",
    "Yang kecil dan membosankan sering menyimpan yang penting dan menentukan.",
    "Kerja rapi hari ini adalah pesan baik untuk auditor bulan depan.",
    "Ketelitian tidak berteriak; ia bekerja dan membiarkan hasilnya bicara.",
    "Jangan takut pada selisih; takutlah pada selisih yang kau abaikan.",
    "Setiap baris punya hak untuk dimengerti sebelum ditutup.",
    "Auditor yang tenang lahir dari catatan yang sudah dicocokkan.",
    "Kebenaran satu angka menular pada kepercayaan seluruh laporan.",
    "Menelusuri memang melelahkan, tetapi menyesal jauh lebih lama.",
    "Ketelitian adalah janji yang kau tepati pada setiap kolom.",
    "Yang teliti tidak lebih pintar, ia hanya menolak berhenti terlalu cepat.",
    "Setiap pencocokan adalah langkah kecil menuju laporan yang bisa dibanggakan.",
    "Angka yang jujur tak butuh pembelaan, cukup kesabaran untuk diperiksa.",
    "Auditor menjaga malam orang lain tetap tenang dengan teliti di siang hari.",
    "Selisih adalah undangan untuk belajar, bukan untuk menyalahkan.",
    "Kerapian bukan soal estetika, melainkan soal dapat dipercaya.",
    "Ketelitian hari ini menutup pintu bagi penyesalan hari esok.",
    "Yang kau pastikan benar tak akan kembali menghantuimu.",
    "Setiap koin yang bertemu pasangannya adalah kemenangan kecil yang nyata.",
    "Auditor sabar bukan karena lambat, tetapi karena tahu harga sebuah kebenaran.",
    "Bekerja teliti adalah cara paling jujur untuk menghormati kepercayaan.",
    "Angka yang tercocokkan tidur; angka yang terabaikan menunggu untuk bangun.",
    "Ketelitian adalah keberanian sunyi yang menjaga banyak orang.",
    "Selesai yang benar lebih berharga daripada selesai yang cepat.",
    "Setiap selisih yang kau bereskan mengembalikan sedikit ketenangan pada dunia angka.",
    "Auditor menutup celah hari ini agar tak ada yang jatuh esok hari.",
    "Yang kau telusuri dengan sabar akan kau tutup dengan bangga.",
    "Ketelitian adalah kebiasaan yang membuat keberuntungan jadi tidak perlu.",
    "Kerja jujur pada angka adalah kerja jujur pada manusia di baliknya.",
    "Setiap laporan bersih menyimpan jejak auditor yang menolak berkompromi.",
    "Menemukan kebenaran satu baris sepadan dengan lelah menelusurinya.",
    "Ketelitian hari ini adalah warisan tenang bagi setiap buku yang kau tutup.",
]

# Motivasi kerja umum.
UMUM = [
    "Mulai dari yang bisa dikerjakan sekarang; sisanya akan menyusul.",
    "Pekerjaan besar selesai satu langkah pada satu waktu.",
    "Istirahat sejenak bukan kalah; ia menjaga ketelitianmu tetap tajam.",
    "Kemajuan kecil tetaplah kemajuan.",
    "Selesaikan yang sulit lebih dulu, sisanya terasa ringan.",
    "Tenang itu produktif; terburu-buru itu boros.",
    "Hari ini cukup satu langkah lebih baik dari kemarin.",
    "Meja yang rapi membantu kepala yang jernih.",
    "Disiplin di hari biasa membentuk hasil yang luar biasa.",
    "Fokus pada prosesnya, hasil akan mengikuti.",
    "Kamu tak harus cepat; kamu hanya perlu terus.",
    "Satu tugas selesai lebih berarti daripada sepuluh yang tertunda.",
    "Nikmati kemajuannya, bukan hanya garis akhirnya.",
    "Kerja yang baik butuh napas yang teratur, bukan hanya tenaga.",
    "Kesabaran hari ini adalah keahlian esok hari.",
    "Berhenti sejenak untuk berpikir bukan membuang waktu, melainkan menghematnya.",
    "Yang penting bukan sempurna, tetapi selesai dengan benar.",
    "Beri dirimu izin untuk teliti, bukan sekadar cepat.",
    "Semangat datang dan pergi; kebiasaan yang membawamu sampai tujuan.",
    "Kerjakan bagianmu hari ini sebaik-baiknya, itu sudah cukup.",
    "Lelah itu wajar; menyerah itu pilihan.",
    "Satu hal pada satu waktu, dikerjakan dengan sungguh-sungguh.",
    "Air tenang menghanyutkan; kerja tenang menuntaskan.",
    "Kualitas adalah kebiasaan, bukan kebetulan.",
    "Hargai usahamu hari ini, sekecil apa pun hasilnya.",
    "Bangun ritme, bukan sekadar mengejar tenggat.",
    "Yang konsisten mengalahkan yang bersemangat sesaat.",
    "Selesaikan yang di depan mata sebelum mengkhawatirkan yang jauh.",
    "Kerja rapi hari ini meringankan langkah esok hari.",
    "Fokus adalah memilih satu hal dan menyelesaikannya.",
    "Kadang langkah terbaik adalah langkah berikutnya, sekecil apa pun.",
    "Tarik napas, lalu lanjutkan satu baris lagi.",
    "Kesungguhan kecil yang berulang membangun hasil yang besar.",
    "Jangan tunggu semangat; mulai saja, semangat menyusul.",
    "Rehat yang cukup adalah bagian dari kerja yang baik.",
    "Yang kau kerjakan dengan hati akan terlihat pada hasilnya.",
    "Sederhanakan, lalu selesaikan.",
    "Hari yang produktif dibangun dari jam-jam yang tenang.",
    "Beri yang terbaik pada tugas di depanmu; itu warisan hari ini.",
    "Tenggat memberi arah, bukan alasan untuk panik.",
    "Setiap tugas yang kau tuntaskan membuat yang berikutnya terasa mungkin.",
    "Bekerja cerdas berarti tahu kapan berhenti dan memeriksa.",
    "Kemajuan yang lambat tetap membawamu maju.",
    "Rawat fokusmu seperti merawat alat kerja yang berharga.",
    "Kerja yang selesai hari ini adalah beban yang tak kau bawa besok.",
    "Yang penting bukan seberapa keras, tetapi seberapa jelas arahmu.",
    "Selesaikan dengan tenang; kualitas tak suka diburu.",
    "Satu kebiasaan baik lebih kuat daripada sepuluh niat besar.",
    "Berikan perhatian penuh pada satu hal, dan ia akan selesai lebih cepat.",
    "Hari ini tak harus sempurna; cukup jujur dan sungguh-sungguh.",
    "Kelola tenagamu, bukan hanya waktumu.",
    "Mulai kecil, tetapi mulai sekarang.",
    "Ketekunan adalah bakat yang bisa dilatih setiap hari.",
    "Kerja yang teratur mengalahkan kerja yang tergesa.",
    "Setiap akhir tugas adalah awal ketenangan yang baru.",
    "Yang kau tunda tak hilang; ia menunggu dengan sabar.",
    "Beri ruang untuk berpikir, dan pekerjaan akan lebih ringan.",
    "Langkah kecil yang konsisten membangun jarak yang jauh.",
    "Selesaikan hari ini dengan bangga, bukan sekadar dengan lega.",
    "Kerja baik adalah rangkaian keputusan kecil untuk tidak asal-asalan.",
]

MOTIVATION = AUDIT + UMUM


def random_quote() -> str:
    """Satu kutipan acak dari pool gabungan (audit + umum)."""
    return random.choice(MOTIVATION)


# Tagline halaman login — nada elegan & profesional soal rekonsiliasi, ketelitian,
# dan kepercayaan uang. Dipilih acak server-side per pemuatan halaman login (lihat
# web.views.AuditorLoginView). Daftar sengaja terpisah dari MOTIVATION agar toast
# dan login tidak saling mengganggu; jaga tetap distinct dari MOTIVATION.
LOGIN_TAGLINES = [
    "Setiap rupiah punya jejak; kami memastikan jejaknya cocok.",
    "Ketika angka bertemu bukti, keraguan berakhir.",
    "Rekonsiliasi yang teliti hari ini, ketenangan yang utuh esok hari.",
    "Panel, Bracket, Bank, Gateway — satu kebenaran dalam satu panel.",
    "Kepercayaan dibangun dari selisih yang dijawab, bukan diabaikan.",
    "Bukan sekadar mencocokkan angka, tapi menjaga integritas tiap transaksi.",
    "Di balik saldo yang seimbang, ada ketelitian yang bekerja diam-diam.",
    "Uang dan koin disandingkan hingga tak ada yang tersembunyi.",
    "Kebenaran finansial lahir dari kesabaran mencocokkan baris demi baris.",
    "Audit yang baik tak berisik; ia hanya memastikan semuanya benar.",
    "Ketepatan adalah bentuk paling sunyi dari kepercayaan.",
    "Satu panel untuk melihat uang dan koin apa adanya.",
]


def random_login_tagline() -> str:
    """Satu tagline acak untuk kartu login. Ringan: O(1)."""
    return random.choice(LOGIN_TAGLINES)
