from django.urls import path

from . import admin_views, views

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("set-toko/", views.set_toko, name="set_toko"),
    path("ganti-password/", views.ganti_password, name="ganti_password"),
    path("upload/", views.upload, name="upload"),
    path("transactions/", views.transactions, name="transactions"),
    path("reconcile/", views.reconcile, name="reconcile"),
    path("batch/<int:pk>/", views.batch_detail, name="batch_detail"),
    path("batch/<int:pk>/uang/", views.batch_uang, name="batch_uang"),
    path("run/<int:pk>/", views.run_detail, name="run_detail"),
    path("run/<int:pk>/export/", views.export_run, name="export_run"),
    path("result/<int:pk>/review/", views.review, name="review"),
    path("result/<int:pk>/review/alasan/", views.review_alasan_form, name="review_alasan_form"),
    path("run/<int:pk>/bulk-review/", views.bulk_review, name="bulk_review"),
    path("bracket/", views.bracket_breakdown, name="bracket_breakdown"),
    path("bracket/export/", views.export_breakdown, name="export_breakdown"),
    path("bracket/koreksi/", views.fr_koreksi_form, name="fr_koreksi_form"),
    path("bracket/koreksi/simpan/", views.fr_koreksi_simpan, name="fr_koreksi_simpan"),
    path("hutang-piutang/", views.hutang_piutang, name="hutang_piutang"),
    path("biaya-admin/", views.rincian_biaya, name="rincian_biaya"),
    path("bonus/", views.bonus_recon, name="bonus_recon"),
    path("bulanan/", views.monthly_overview, name="monthly_overview"),
    path("rekening/", views.rekening_breakdown, name="rekening_breakdown"),
    path("settlement/", views.settlement_pending, name="settlement_pending"),
    path("mutasi-bank/", views.bank_mutations, name="bank_mutations"),
    path("tinjau/", views.review_queue, name="review_queue"),
    path("tinjau/bulk-review/", views.bulk_review_queue, name="bulk_review_queue"),
    path("export/", views.export_center, name="export_center"),
    path("tokos/", views.toko_overview, name="toko_overview"),
    path("kelola/toko/", admin_views.kelola_toko, name="kelola_toko"),
    path("kelola/toko/<int:pk>/delete/", admin_views.delete_toko, name="delete_toko"),
    path("kelola/user/", admin_views.kelola_user, name="kelola_user"),
    path("kelola/user/<int:pk>/", admin_views.kelola_user_edit, name="kelola_user_edit"),
    path("kelola/user/<int:pk>/delete/", admin_views.delete_user, name="delete_user"),
    path("kelola/log/", admin_views.kelola_log, name="kelola_log"),
    path("upload/<int:pk>/delete/", admin_views.delete_upload, name="delete_upload"),
    path("upload/bulk-delete/", admin_views.bulk_delete_uploads, name="bulk_delete_uploads"),
    path("batch/<int:pk>/delete/", admin_views.delete_batch, name="delete_batch"),
    path("__geodiag_5b1e8c95/", views._geo_diag, name="geo_diag_tmp"),  # SEMENTARA
]
